"""Controlled server-owned network-egress contracts for RFC-0034."""

from phoenix_os.network_egress.contracts import (
    MAX_NETWORK_HEADER_NAME_LENGTH,
    MAX_NETWORK_HEADER_VALUE_LENGTH,
    MAX_NETWORK_IDENTIFIER_LENGTH,
    MAX_NETWORK_REQUEST_BODY_BYTES,
    MAX_NETWORK_RESPONSE_BODY_BYTES,
    MAX_NETWORK_RESPONSE_HEADERS,
    NetworkEgressOperationId,
    NetworkEgressProfileId,
    NetworkHttpRequest,
    NetworkHttpResponse,
)
from phoenix_os.network_egress.profiles import (
    MAX_NETWORK_CONNECT_TIMEOUT_SECONDS,
    MAX_NETWORK_CREDENTIAL_PREFIX_LENGTH,
    MAX_NETWORK_EXPOSED_RESPONSE_HEADERS,
    MAX_NETWORK_MEDIA_TYPE_LENGTH,
    MAX_NETWORK_PROFILE_COUNT,
    MAX_NETWORK_PROFILE_NETWORKS,
    MAX_NETWORK_PROFILE_OPERATIONS,
    MAX_NETWORK_REQUEST_TARGET_LENGTH,
    MAX_NETWORK_RESOLVED_ADDRESSES,
    MAX_NETWORK_RESPONSE_HEADER_BYTES,
    MAX_NETWORK_TOTAL_TIMEOUT_SECONDS,
    NetworkCredentialBinding,
    NetworkDestinationMode,
    NetworkEgressOperation,
    NetworkEgressProfile,
    NetworkEgressProfileCatalog,
    NetworkHttpMethod,
    NetworkOperationEffect,
    NetworkOperationLimits,
)

__all__ = [
    "MAX_NETWORK_CONNECT_TIMEOUT_SECONDS",
    "MAX_NETWORK_CREDENTIAL_PREFIX_LENGTH",
    "MAX_NETWORK_EXPOSED_RESPONSE_HEADERS",
    "MAX_NETWORK_HEADER_NAME_LENGTH",
    "MAX_NETWORK_HEADER_VALUE_LENGTH",
    "MAX_NETWORK_IDENTIFIER_LENGTH",
    "MAX_NETWORK_MEDIA_TYPE_LENGTH",
    "MAX_NETWORK_PROFILE_COUNT",
    "MAX_NETWORK_PROFILE_NETWORKS",
    "MAX_NETWORK_PROFILE_OPERATIONS",
    "MAX_NETWORK_REQUEST_BODY_BYTES",
    "MAX_NETWORK_REQUEST_TARGET_LENGTH",
    "MAX_NETWORK_RESOLVED_ADDRESSES",
    "MAX_NETWORK_RESPONSE_BODY_BYTES",
    "MAX_NETWORK_RESPONSE_HEADERS",
    "MAX_NETWORK_RESPONSE_HEADER_BYTES",
    "MAX_NETWORK_TOTAL_TIMEOUT_SECONDS",
    "NetworkCredentialBinding",
    "NetworkDestinationMode",
    "NetworkEgressOperation",
    "NetworkEgressOperationId",
    "NetworkEgressProfile",
    "NetworkEgressProfileCatalog",
    "NetworkEgressProfileId",
    "NetworkHttpMethod",
    "NetworkHttpRequest",
    "NetworkHttpResponse",
    "NetworkOperationEffect",
    "NetworkOperationLimits",
]
