"""Phoenix Capability Registry public API."""

from phoenix_os.capabilities.adapter import (
    CapabilityContextFactory,
    CapabilityHandler,
    request_context,
)
from phoenix_os.capabilities.contracts import (
    CapabilityArguments,
    CapabilityContext,
    CapabilityDescriptor,
    CapabilityInvocation,
    CapabilityMetadata,
    CapabilityOutput,
    CapabilityProvider,
    CapabilityRegistration,
    CapabilityResult,
    ConfirmationDecision,
    ConfirmationPolicy,
    ConfirmationStatus,
    PermissionDecision,
    PermissionPolicy,
    PermissionStatus,
    RiskLevel,
)
from phoenix_os.capabilities.errors import (
    CapabilityAlreadyRegisteredError,
    CapabilityConfirmationRequiredError,
    CapabilityDeadlineExceededError,
    CapabilityError,
    CapabilityExecutionError,
    CapabilityNotFoundError,
    CapabilityPermissionDeniedError,
    CapabilityPolicyError,
    CapabilityRegistryClosedError,
)
from phoenix_os.capabilities.policies import (
    AllowAllPermissionPolicy,
    DescriptorConfirmationPolicy,
    NeverRequireConfirmationPolicy,
    RequiredPermissionsPolicy,
)
from phoenix_os.capabilities.registry import CapabilityRegistry

__all__ = [
    "AllowAllPermissionPolicy",
    "CapabilityAlreadyRegisteredError",
    "CapabilityArguments",
    "CapabilityConfirmationRequiredError",
    "CapabilityContext",
    "CapabilityContextFactory",
    "CapabilityDeadlineExceededError",
    "CapabilityDescriptor",
    "CapabilityError",
    "CapabilityExecutionError",
    "CapabilityHandler",
    "CapabilityInvocation",
    "CapabilityMetadata",
    "CapabilityNotFoundError",
    "CapabilityOutput",
    "CapabilityPermissionDeniedError",
    "CapabilityPolicyError",
    "CapabilityProvider",
    "CapabilityRegistration",
    "CapabilityRegistry",
    "CapabilityRegistryClosedError",
    "CapabilityResult",
    "ConfirmationDecision",
    "ConfirmationPolicy",
    "ConfirmationStatus",
    "DescriptorConfirmationPolicy",
    "NeverRequireConfirmationPolicy",
    "PermissionDecision",
    "PermissionPolicy",
    "PermissionStatus",
    "RequiredPermissionsPolicy",
    "RiskLevel",
    "request_context",
]
