"""Public Plugin System and Adapter SDK surface."""

from phoenix_os.plugins.contracts import (
    PHOENIX_VERSION,
    PLUGIN_API_VERSION,
    Plugin,
    PluginContext,
    PluginDependency,
    PluginExports,
    PluginFailure,
    PluginFailurePhase,
    PluginHook,
    PluginManagerState,
    PluginManifest,
    PluginPermission,
    PluginReference,
    PluginRegistration,
    PluginSnapshot,
    PluginStatus,
    SemanticVersion,
    VersionRange,
    normalize_plugin_id,
)
from phoenix_os.plugins.discovery import EntryPointPluginDiscovery
from phoenix_os.plugins.errors import (
    PhoenixPluginError,
    PluginAlreadyRegisteredError,
    PluginCompatibilityError,
    PluginDependencyCycleError,
    PluginDependencyError,
    PluginDiscoveryError,
    PluginExportError,
    PluginNotFoundError,
    PluginPermissionDeniedError,
    PluginSetupError,
    PluginStartError,
    PluginStateError,
    PluginStopError,
)
from phoenix_os.plugins.manager import PluginManager
from phoenix_os.plugins.sdk import HookPlugin, PluginRegistrar, plugin_services

__all__ = [
    "PHOENIX_VERSION",
    "PLUGIN_API_VERSION",
    "EntryPointPluginDiscovery",
    "HookPlugin",
    "PhoenixPluginError",
    "Plugin",
    "PluginAlreadyRegisteredError",
    "PluginCompatibilityError",
    "PluginContext",
    "PluginDependency",
    "PluginDependencyCycleError",
    "PluginDependencyError",
    "PluginDiscoveryError",
    "PluginExportError",
    "PluginExports",
    "PluginFailure",
    "PluginFailurePhase",
    "PluginHook",
    "PluginManager",
    "PluginManagerState",
    "PluginManifest",
    "PluginNotFoundError",
    "PluginPermission",
    "PluginPermissionDeniedError",
    "PluginReference",
    "PluginRegistrar",
    "PluginRegistration",
    "PluginSetupError",
    "PluginSnapshot",
    "PluginStartError",
    "PluginStateError",
    "PluginStatus",
    "PluginStopError",
    "SemanticVersion",
    "VersionRange",
    "normalize_plugin_id",
    "plugin_services",
]
